DATA SEGMENT
STR1 DB 'HOW ARE YOU?'
LEN EQU $-STR1
FORWARD DB 20 DUP(0)
DATA ENDS
CODE SEGMENT
;start of data segment
;end of data segment
;start of code segment
ASSUME CS:CODE,DS:DATA,ES:DATA
START: MOV AX,DATA
MOV DS,AX
MOV ES,AX

LEA SI,STR1
LEA DI,FORWARD
MOV CX,LEN
CLD
REP MOVSB

MOV AH,4CH
INT 21H
CODE ENDS
END START